name: iOS CI/CD


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install --repo-update


      - name: Install fastlane
        run: gem install fastlane

    
      - name: Build app
        run: |
          xcodebuild clean build \
            -workspace YourApp.xcworkspace \
            -scheme YourAppScheme \
            -sdk iphoneos \
            -configuration Release \
            ONLY_ACTIVE_ARCH=NO

    
      - name: Run Tests
        run: |
          xcodebuild test \
            -workspace YourApp.xcworkspace \
            -scheme YourAppScheme \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0'

      
      - name: Deploy to TestFlight
        if: github.ref == 'refs/heads/main'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: fastlane ios beta